api/dsService/dsRouter.js

Created Skeleton for data/data update
Will need to program a bot to make that call whenever we decide how often the DS side will update.

DS Skeleton Added and Commented

---

.env.sample
api/cases/caseRouter.js
api/judges/judgeModel.js
api/judges/judgeRouter.js
api/middleware/verifyDataID.js

Verify Judge & Case Middleware

This pre commit hook is a pain. Updated Middleware

---

api/cases/caseModel.js
api/cases/caseRouter.js
api/judges/judgeModel.js
api/judges/judgeRouter.js
api/middleware/verifyDataID.js
api/profile/profileModel.js
api/profile/profileRouter.js
data/migrations/20201202180934_judges.js
data/migrations/20201202194136_cases.js
data/migrations/20201202232058_book_mark_judges.js
data/migrations/20201202232116_book_mark_cases.js
data/seeds/001_profiles.js
data/seeds/002-judges.js
data/seeds/003-cases.js

Wingfield judge joins

---

api/cases/caseModel.js
api/cases/caseRouter.js
api/judges/judgeModel.js
api/judges/judgeRouter.js
api/middleware/verifyDataID.js
api/profile/profileModel.js
api/profile/profileRouter.js
data/migrations/20201202180934_judges.js
data/migrations/20201202194136_cases.js
data/migrations/20201202232058_book_mark_judges.js
data/migrations/20201202232116_book_mark_cases.js
data/seeds/001_profiles.js
data/seeds/002-judges.js
data/seeds/003-cases.js

joined book marks for cases/judges on profiles.

Wingfield profile join

---

api/dsService/dsRouter.js
api/judges/judgeRouter.js
api/profile/profileModel.js
api/profile/profileRouter.js

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[x ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Tests
[ ] Other
```
- Description
- Example: 
Added Add/Remove Bookmark Endpoints & Routes

Wingfield book marks

---

api/profile/profileModel.js
api/profile/profileRouter.js
utils/AWS.js

Updates for Tom!

---

api/dsService/dsRouter.js
package-lock.json
package.json
utils/update.js

When DS finishes getting their data online, we can uncomment the code.
Two options are fleshed out for timing.

CronJob created and commented out. 

---

api/profile/profileModel.js
package-lock.json
package.json
utils/cache.js

Minor tweak to profile model. Beginnings of cache system.

---

api/dsService/dsModel.js
api/dsService/dsRouter.js
utils/AWS.js

Can now upload form data as a JSON

JSON2CSV, form upload implemented

---

api/cases/caseRouter.js
api/dsService/dsRouter.js
api/judges/judgeRouter.js
api/keywords/keywordsRouter.js
api/middleware/cache.js
api/tags/tagRouter.js
temp.tgz

Bug fix.
Fixed caching errors across the board.
AWS should come in this afternoon.

Fixed the bug AND increased parsing time.

---

api/cases/caseRouter.js
api/dsService/dsRouter.js
api/judges/judgeRouter.js
api/keywords/keywordsRouter.js
api/profile/profileRouter.js
api/tags/tagRouter.js
config/jsdoc.js
temp.tgz

Swagger Documentation Completed for all normal GET req's.
Tomorrow I'll do the POST and DELETE.
Docs for POST and GET files will come after the AWS comes in.

Wingfield swagger profile

---

api/judges/judgeModel.js
api/judges/judgeRouter.js

Added functions to support Judge Page charts & data

Wingfield final judge

---

api/judges/judgeModel.js

The update is tested manually and locally and I confirm that it does not break the code. The failing tests are inherited from the previous team. We'll fix them later.

Fix the ESLint error regarding `hasOwnProperty`

---

api/profile/profileModel.js
api/profile/profileRouter.js
data/migrations/20200625220949_create-profile.js
data/seeds/001-profiles.js
package-lock.json
package.json

adjusted migrations and seed data to accommodate for these changes

implemented okta client with user creation

---

api/app.js

Hopefully this fixes deployment

---

config/knexfile.js
data/db-config.js

Yet another fix for the deployed website
Needed in order to migrate all the DB updates to heroku

Updates to DB configs to fix deployment

---

api/upload/uploadRouter.js

Just updating the upload stuff to use auth properly, gotta have security :)

Adding auth to upload router

---

KnownDefects.md
README.md
api/APIDOC.md
api/README.md

Documentation separated different files

New documentation implemented

---

api/upload/uploadModel.js
api/upload/uploadRouter.js
config/knexfile.js

- create changeStatus function that takes in an id and a status to change to 
- changeStatus will update from 'pending' to 'review' once the scraped data is returned

add changeStatus function to update progress of cases

---

api/profile/profileModel.js
api/profile/profileRouter.js

- saves judge to database
- successfully deletes judge
- responds with updated saved_judges after deletion
- There is a bug that occurs after trying to delete the judge. Error is coming from params on frontend. Need to inspect how MUI is updating. Code that introduces bug is commented out for now. The rest of the function works smoothly.

delete saved judge based on judge id

---

api/cases/caseModel.js
api/cases/caseRouter.js
api/pendingCases/pendingCaseRouter.js
api/upload/uploadRouter.js

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
User's pending cases table was not populating, there were a couple issues causing this:
- Because user was changed to user_id in database schema, this change needed to be reflected in endpoints using req.profile.id. They now use req.profile.user_id
- The case model had a couple functions still using judge instead of judge_id

req.profile.id -> req.profile.user_id, judge -> judge_id

---

api/judges/judgeModel.js
api/upload/uploadRouter.js

quick bug fix for judge_id

---

api/profile/profileModel.js

- saves cases and uses appropriate column name

saves cases:

---

api/faq/faqModel.js
api/faq/faqRouter.js

Delete, create, edit FAQ for admin

---

api/profile/profileModel.js
api/profile/profileRouter.js
package-lock.json

- admin can create, read, delete, update user
- note: errors don't sync with Okta. This means that changes can be seen on your local but may not reflect what's on Okta db. Will need to look into this more.

admin can create, read, update, delete user

---

api/cases/caseModel.js
api/cases/caseRouter.js

Model and Router endpoints for number of cases by state.

Data Viz endpoint, number of cases by state

---

api/profile/profileRouter.js
data/migrations/20210419194303_pending_profiles.js

- adds role to pending_profiles table & firstName -> first_name, lastName -> last_name
- above done in migration file for pending_profiles, rollback and migration required to see changes locally
- corresponds to frontend changes made to admin/user flows
- recommend rolling back migration before you incorporate locally to avoid issues as firstName and latName fields are now 'missing'
- helps address issues with adding, rejecting, & editing user info from ManageUsers page

Changes to pending_profiles table in db schema

---

api/profile/profileModel.js
api/profile/profileRouter.js

- changes update users function in profile model
- corresponding change in put response in profile router
- supports change from EditUser page to edit user modal

Update Users Endpoint Change

---

api/judges/judgeRouter.js
api/profile/profileModel.js
api/profile/profileRouter.js

Previously, saved cases was returning only the case information. This excluded information like the judge associated with the case. More information is contained for the saved cases now. 
- cleaned files

removed console.logs and return useable case information for saved cases

---

api/judges/judgeRouter.js

This PR updates the judgerouter endpoint for interfacing with the DS API to properly parse their response before sending back to the front-end.

Updates JudgeRouter

---

data/seeds/010-pending_cases.js

-made seed data for pending_cases

seed update for pending_cases

---

api/profile/profileRouter.js

- PUT response correctly returns the latest updated profile 
I think there would needs to be a more reliable to return the correct user in the future.

updating user info also returns the user that was just changed

---

.env.sample

adds an example for Database URL in .env.sample file

---

README.md
api/cases/caseModel.js
api/cases/caseRouter.js

Juan and I added a put request to edit the case comment from 'Null' to whatever the admin types in. We added a put request in caseRouter and updateComment in the caseModel. We then updated the README.md documentation for this route.
Allows FE to update comment status from Null to a new comment. 
Added a new BE endpoint for the FE to access.

updated the comments api request

---

api/cases/caseModel.js

temporarily commented out a join in `caseModel.js` that is causing the returned cases to be inaccurate.
This should FINALLY fix the uploads.

Remove a join to FINALLY fix uploads

---

api/cases/caseRouter.js

Fixed some mismatched parentheses and braces in caseRouter.js which were preventing the server from compiling.

fixed syntax errors which prevented compilation

---

api/dsService/dsRouter.js
api/judges/judgeModel.js
api/judges/judgeRouter.js
data/migrations/20200625220949_create_profile.js

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixed the endpoint requesting judge data and sending it to datascience

Fixed judge endpoint and model

---

api/upload/uploadRouter.js

added some cases to switch statement to handle data coming from alternate DS ocr endpoint. Changed api call from POST to GET.

Hopefully Fix uploads again

---

api/cases/caseModel.js
api/cases/caseRouter.js
api/upload/uploadRouter.js

So many console logs you wouldnt know what was going on

Added a ton of console logs

---

api/upload/uploadRouter.js

adding dir to see object parameters

---

api/upload/uploadRouter.js

Added two new console logs and removed old ones

---

api/upload/uploadRouter.js

Updated .update to match with modern function parameters.

Fixed update to work with current feature

---

server.js

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

change timeout to flat rate

---

api/cases/caseModel.js
api/upload/uploadRouter.js

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixed the update to work properly with model sent.
Removed console logs

Fixed cases update model and removed console logs from upload

---

README.md
api/app.js
api/roles/rolesModel.js
api/roles/rolesRouter.js

- Created roles model to query roles table
- Created roles router to setup endpoints in the api for role GET and PUT
- Added roles router to main app
- Updated documentation to include roles endpoints and schema
- Needed GET endpoints for front end to draw information about role name/id pairs
- Added PUT as easy way to change role names
- Larger context of updating application-wide permissions for different roles to be more secure, and implementing moderator role

Feature/roles endpoints/repush

---

api/cases/caseRouter.js
api/faq/faqRouter.js
api/middleware/onlyRoles.js
api/profile/profileRouter.js
api/roles/rolesRouter.js

- onlyRoles middleware created which allows endpoints to be restricted to certain roles
- onlyRoles middleware contains exceptions for users to read and update their own data
- onlyRoles has been added to all endpoints only used in admin tools components
- Security vulnerability on the front end allows anyone to gain admin rights and access/edit/delete sensitive data
- Back end verification of user role for role-restricted endpoints fixes issue without changing front end
- Front end may also patch this in the future?
Fixes # Security Vulnerability

Feature/auth role/rpeck

---

README.md
api/judges/judgeRouter.js

Implemented endpoint at 'judge/:judge_id/vis' to provide JSON data object produced by DS API. Current DS implementation queries the DB using the first name, which should be refactored to query via ID, for normalization reasons.
Some readme updates 
New endpoint for Judge Data

Implemented judge endpoint for JSON plotly data

---

README.md

Adds the architecture graphic from the Data Science readme to this repo. Provides a valuable, visual description of the interactions between Oka, Heroku, AWS, Postgres, and more.

Add Architecture graphic from DS readme to BE readme
